name: hallo
description: A new project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  dio: ^5.5.0+1
  collection: ^1.19.1
  http: ^1.2.0
  latlong2: ^0.9.0
  google_maps_flutter: ^2.14.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  flutter_map: ^7.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
