name: agroboost_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

flutter: 
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
    # gestion d'état
  provider: ^6.0.5 
  flutter_localizations:
    sdk: flutter

  # géolocalisation
  geolocator: ^11.0.0 

  # requêtes HTTP
  dio: ^5.0.0 # alternative à 'http', plus orienté pour la gestion des services.

  # configuration
  flutter_dotenv: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.12.0

    
dev_dependencies:
  flutter_lints: ^6.0.0
